name: Update Contributions

on:
  schedule:
    - cron: 0 0 */2 * *
  workflow_dispatch:

jobs:
  temporary:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: pnpm ci
      - run: pnpm dev
