name: Update Contributions

on:
  schedule:
    - cron: 0 0 */2 * *
  workflow_dispatch:

jobs:
  temporary:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Starting..."
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install Dependencies
        run: npm install
      - name: Run Script
        run: npm run dev
        env: GITHUB_TOKEN:${{ secrets.GITHUB_TOKEN }}
      - run: echo "Done"
